### ISSUE TITLE
Investigate this bug

### ISSUE THREAD

**Issue by Big-Laundry** [Hamster-Huey/S3BotCmd#29]
Saw this in logs:
Received absences request for date 12/20/2018 00:00:00 from channel leadership from user HamsterHuey
Looking up absence sheet
Replying
Received absences request for date 01/11/2018 00:00:00 from channel dev-test from user HamsterHuey
Looking up absence sheet
Replying
17:41:37 Gateway     A MessageReceived handler is blocking the gateway task.
17:42:20 Gateway     System.Exception: Server missed last heartbeat
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<>c__DisplayClass28_0.<<StartAsync>b__0>d.MoveNext()
17:42:20 Gate

**Comment by Big-Laundry** [comment]
https://github.com/RogueException/Discord.Net/issues/616 

Potentially need to set RunMode = RunMode.Async

**Comment by Big-Laundry** [comment]
https://github.com/RogueException/Discord.Net/issues/904 

Or potentially azure issue

**Comment by Big-Laundry** [comment]
https://github.com/Hamster-Huey/S3BotCmd/issues/27 

If anything, let's get this going, and let the container auto-restart if ever gets to particular state. 

And work on this particular fix:
https://github.com/Hamster-Huey/S3BotCmd/issues/21
